language: node_js
node_js:
  - 14
cache:
  directories:
    - ./node-modules

stage:
  - test
  - build and deploy
  - deployment

install:
  - npm install -g @angular/cli
  - npm install
  - ng add angular-cli-ghpages

jobs:
  include:
    - stage: test
      script:
        - ng test --watch=false --browsers ChromeHeadless
    - stage: build
      script:
        - ng build --prod --base-href /mycargonaut/
    - stage: deployment
      script:
        - ng deploy --base-href /mycargonaut/
      branches:
        only:
          - main









