language: node_js
node_js:
  - 14
cache:
  directories:
    - ./node-modules

stage:
  - test
  - build
  - deployment

install:
  - npm install -g @angular/cli
  - npm install

jobs:
  include:
    - stage: test
      script:
        - ng test --watch=false --browsers ChromeHeadless
    - stage: build
      script:
        - ng build --prod --base-href /mycargonaut/
    - stage: deployment
      script:
        - ng deploy --base-href /mycargonaut/
      on:
        branch: main


#      before_deploy:
#        - cd dist/mycargonaut
#        - cp dist/mycargonaut/index.html dist/mycargonaut/404.html
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: $GITHUB_TOKEN
#        keep_history: true
#        local_dir: dist/mycargonaut
#        on:
#          branch: main









