language: node_js
node_js:
  - 14
cache: npm

branches:
  only:
    - main
    - dev

install:
  - npm install -g @angular/cli
  - npm install
  - ng add angular-cli-ghpages

script:
  - ng test --watch=false --browsers ChromeHeadless
#  - ng build --prod --base-href /mycargonaut/
#  - ng deploy --base-href /mycargonaut/

before_deploy:
  - ng build --prod --base-href /mycargonaut/
  - cp dist/mycargonaut/index.html dist/mycargonaut/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/mycargonaut
  on:
    branch: main


