language: node_js
node_js:
  - 14
cache: npm

branches:
  only:
    - main

install:
  - npm install

script:
  - npm run test --watch=false --browsers ChromeHeadless

before_deploy:
  - npm run build --base-href /mycargonaut/
  - cp dist/mycargonaut/index.html dist/mycargonaut/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/mycargonaut
  on:
    branch: main


