language: node_js
node_js:
  - 14
cache:
  directories:
    - ./node-modules

stages:
  - name: test
  - name: build and deploy
  - name: deployment
    if: branch = main

install:
  - npm install -g @angular/cli
  - npm install

jobs:
  include:
    - stage: test
      script:
        - ng test --watch=false --browsers ChromeHeadless
    - stage: build
      script:
        - ng build --prod --base-href /mycargonaut/
    - stage: deployment
      script:
        - ng add angular-cli-ghpages
        - ng deploy --base-href /mycargonaut/






