language: node_js
node_js:
  - 14
cache: npm

branches:
  only:
    - main
    - dev

install:
  - npm install -g @angular/cli
  - npm install

before_script:
  - ng add angular-cli-ghpages

script:
  - ng test --watch=false --browsers ChromeHeadless
  - ng deploy --base-href /mycargonaut/

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN
#  keep_history: true
#  local_dir: dist/mycargonaut
#  on:
#    branch: main


