language: node_js
node_js:
  - 14
cache: npm

branches:
  only:
    - main

install:
  - npm install -g @angular/cli
  - npm install

script:
  - ng test --watch=false --browsers ChromeHeadless

before_deploy:
  - ng build --prod --base-href /mycargonaut/
  - cp dist/mycargonaut/index.html cp dist/mycargonaut/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/mycargonaut
  on:
    branch: main


